version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Install MinGW for cross-compile
          command: sudo apt -y install binutils-mingw-w64 gcc-mingw-w64 gcc-multilib
      - run:
          name: Greeting
          command: echo "A first hello"
      - run:
          name: Simple build
          command: make
      - run:
          name: Clean after simple build
          command: make clean
      - run:
          name: Build for every platform at once (except macOS)
          command: make build
      - run:
          name: Clean after cross-platform build
          command: make build_clean
